device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False
num_workers: 4

checkpoint_load:
checkpoint_save:
log:
dataset_path: '../data'

val_ratio: 0.1
epochs: 100
batch_size: 256
lr: 0.01
lr_scheduler: CosineAnnealingLR

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

index: 

acc_ratio: 0.1 #for fair
print_every: 500 
nb_iter: 2000
anp_eps: 0.4
anp_steps: 1
anp_alpha: 0.2
pruning_by: 'threshold'
pruning_max: 0.90 
pruning_step: 0.05