device: 'cuda'
amp: True
non_blocking: True
num_workers: 4

dataset_path: '../data/cifar10'
dataset: 'cifar10'

epochs: 100
frequency_save: 0
batch_size: 256

lr: 0.01
lr_scheduler: CosineAnnealingLR

pin_memory: True
prefetch: False
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005

acc_ratio: 0.1
val_ratio: 0.1
once_prune_ratio: 0.01
index: