device: 'cuda'
dataset_path: '../data'

amp: True
pin_memory: True
non_blocking: True
prefetch: False
num_workers: 4

checkpoint_load:
checkpoint_save:
log:

epochs: 100
batch_size: 256
lr: 0.01
lr_scheduler: CosineAnnealingLR

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0