device: 'cuda'
dataset_path: '../data'

num_classes: 
input_height: 
input_width:
input_channel:

batch_size: 256
num_workers: 4

pin_memory: True
prefetch: False
non_blocking: True

lr: 0.1
lr_min: 0.02
momentum: 0.95
weight_decay: 1e-4


l1_weight: 0.001
beta: 0.5
alpha: 0.8

epochs: 100