device: 'cuda'
dataset_path: '../data'

num_classes: 
input_height: 
input_width:
input_channel:

batch_size: 256
num_workers: 4

training_epochs: 20
adv_train_iters: 7
adv_train_eps: 0.02
adv_train_alpha_scale: 5.0
lr: 0.01

pin_memory: True
prefetch: False
non_blocking: True