device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False
num_workers: 4

checkpoint_load:
checkpoint_save:
log:
dataset_path: '../data'
dataset: 'tiny'

epochs: 100
batch_size: 256

lr: 0.0001
lr_scheduler: CosineAnnealingLR

client_optimizer: 'adam'
sgd_momentum: 0.9 
wd: 0
adam_betas: [0.9, 0.999]
frequency_save: 0

index: 
n_rounds: 5
K: 5