# Device and hardware settings
device: "cuda"                  # "cuda" or "cpu"
pin_memory: True                # for dataloader: pin memory (true/false)
non_blocking: False             # whether to use non-blocking transfers
prefetch: False                 # whether to use prefetching
amp: True                       # Automatic Mixed Precision flag

dataset_path: '../data'  # path to the dataset
dataset: 'cifar10'
size: 32                        # size of the input image

checkpoint_load:
checkpoint_save:
log:

batch_size: 128                    # batch size for dataloaders
num_workers: 4                    # number of worker processes for dataloaders

# Randomness and config file path
random_seed: 42                  # random seed for reproducibility

# Parameters specific to UNet training (train_unet)
gen_lr: 0.001                 # learning rate for the UNet generator optimizer
preround: 50                   # number of rounds for pretraining the generator

# Parameters specific to mitigation (run_mitigation)
cls_lr: 0.0001                  # learning rate for classifier update during mitigation
mround: 20                     # number of rounds for mask-generator training in "reverse"
uround: 30                     # number of rounds for backdoor generator training in "reverse"
norm_bound: 0.3               # threshold for loss_norm condition in reverse
feat_bound: 3               # threshold for loss on benign features in reverse
ul_round: 30                  # number of rounds for the unlearning phase
nround: 5                     # number of mitigation rounds (outer loop)
earlystop: False               # flag to enable early stopping in mitigation