device: 'cuda'
dataset_path: '../data'

dataset: 'cifar10'
num_classes: 
input_height: 
input_width:
input_channel:

batch_size: 256
num_workers: 0 

training_epochs: 10
lr: 0.01
alpha: 0.2

pin_memory: True
prefetch: False
non_blocking: True