device: 'cuda'
dataset_path: '../data'

dataset: 'tiny'
num_classes: 
input_height: 
input_width:
input_channel:

batch_size: 256
num_workers: 4

training_epochs: 15
lr: 0.001
alpha: 0.001

pin_memory: True
prefetch: False
non_blocking: True